[package]
name = "imgui_rs_example"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
imgui = "0.12.0"
imgui-winit-support = "0.13.0"
imgui-wgpu = "0.25.0"
wgpu = "*"
winit = "*"
pollster = "*"